version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - run:
          name: Install Npm packages
          command: npm install
      - run:
          name: Build with yarn
          command: yarn prod-build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
