# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8.9
#     steps:
#       - checkout
#       - run:
#         name: update-npm
#         command: 'sudo npm install -g npm@latest'
#       - run:
#         name: "Checking Versions"
#         command: |
#           node --version
#           npm --version
#       - run:
#           name: Install Npm packages
#           command: npm install
#       - run: yarn prod-build
#   deploy-job:
#     docker:
#       - image: circleci/node:8.9
#         working_directory: /tmp/my-project
#     steps:
#       - run:
#           name: Deploy Master to Firebase
#           command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy-job:
#         requires:
#           - build
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: node --version
  deploy:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm --version
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
