version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install Npm packages
          command: npm install
            paths:
              - node_modules
      - run: yarn prod-build

  # deploy-job:
  #   docker:
  #     - image: circleci/node:7.10
  #   working_directory: /tmp/my-project
  #   steps:
  #     - run:
  #         name: Deploy Master to Firebase
  #         command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-job:
        requires:
          - build
        filters:
        branches:
          only: master
